apiVersion: v1
kind: Service
metadata:
  name: k8s-test-service
spec:
  selector:
    app: k8s-test
  ports:
    - name: http
      port: 8020
      targetPort: app
      nodePort: 8020
  type: NodePort
